<a href="https://colab.research.google.com/github/tarushsingh09/Weather_Sequence_predict_using_HMM_Model/blob/main/E21CSEU0974_NLP_LAB_4_HMM_MODEL_WEATHER_SEQUENCE_TARUSH_SINGH_EB_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TARUSH SINGH
#E21CSEU0974
#EB-13
#NLP Lab Assignment – 04: Predict the weather sequence
#Objective: In this assignment, you will implement an HMM model to predict the weather
#sequence for the given observation sequence.
#Task: What is the probability of the observed sequence- 1,3,1 given the parameters of the HMM?


In [2]:
import numpy as np

# Define the HMM parameters
# Number of states
num_states = 2

# Transition matrix
transition_matrix = np.array([
    [0.5, 0.5],  # Transition from COLD to [COLD, HOT]
    [0.4, 0.6]   # Transition from HOT to [COLD, HOT]
])
print("Transition Matrix:")
print(transition_matrix)

Transition Matrix:
[[0.5 0.5]
 [0.4 0.6]]


In [3]:
# Emission probabilities
emission_probabilities = np.array([
    [0.5, 0.4, 0.1],  # COLD state emissions for observations [1, 3, 1]
    [0.2, 0.4, 0.4]   # HOT state emissions for observations [1, 3, 1]
])
print("Emission probabilities: ")
print(emission_probabilities)

Emission probabilities: 
[[0.5 0.4 0.1]
 [0.2 0.4 0.4]]


In [4]:
# Initial state probabilities (pi)
initial_probabilities = np.array([0.2, 0.8])  # [COLD, HOT]
print("Initial state probabilities: ")
print(initial_probabilities)

Initial state probabilities: 
[0.2 0.8]


In [5]:
# Observed sequence: 1, 3, 1
observed_sequence = [0, 2, 0]  # Assuming 0 represents observation 1, 1 represents observation 2, and 2 represents observation 3

def forward_algorithm(observed_sequence, initial_probabilities, transition_matrix, emission_probabilities):
    num_states, num_observations = len(initial_probabilities), len(observed_sequence)
    forward_matrix = np.zeros((num_states, num_observations))

    # Initialization
    for state in range(num_states):
        forward_matrix[state, 0] = initial_probabilities[state] * emission_probabilities[state, observed_sequence[0]]

    # Recursion
    for t in range(1, num_observations):
        for state in range(num_states):
            forward_matrix[state, t] = sum(forward_matrix[prev_state, t - 1] * transition_matrix[prev_state, state] * emission_probabilities[state, observed_sequence[t]]
                                           for prev_state in range(num_states))

    # Termination
    probability = sum(forward_matrix[state, num_observations - 1] for state in range(num_states))

    return forward_matrix, probability

# Calculate the forward matrix and probability
forward_matrix, probability = forward_algorithm(observed_sequence, initial_probabilities, transition_matrix, emission_probabilities)

print("Forward Matrix:")
print(forward_matrix)
print("\nProbability of the Observed Sequence:", probability)


Forward Matrix:
[[0.1      0.0114   0.01453 ]
 [0.16     0.0584   0.008148]]

Probability of the Observed Sequence: 0.022678000000000007
